orbs:
  nexus-orb: orbtest/circleci-nexus-orb@dev:INT-2218

version: 2.1 # use CircleCI 2.1
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package -DskipTests -DskipITs
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      
      - nexus-orb/install

      - run: pwd

      - run: ls -al $(pwd)
      
      - run: ls -al $(pwd)/target
      
      - run: echo ${CIRCLE_WORKING_DIRECTORY}

      - run: ls -al ~/circleci-demo-java-spring/target/demo-java-spring-0.0.1-SNAPSHOT.jar
     
      - nexus-orb/publish:
          workspace: "$(pwd)"
          filename: "target/demo-java-spring-0.0.1-SNAPSHOT.jar"
          attributes: "-CgroupId=com.example -CartifactId=myapp -Cversion=1.3 -Aextension=jar"
          username: "${NEXUS_RM_USERNAME}"
          password: "${NEXUS_RM_PASSWORD}"
          serverurl: "${NEXUS_RM_SERVERURL}"
